-- Carga inicial: PRESTADOR, USUARIO e USUARIO_PERFIL.
-- Nomes dos prestadores vieram da planilha da UG.
-- Documento, endereco, telefone, e-mail e senha sao ficticios.
-- Senha de todos: senha123

SET DEFINE OFF

DELETE FROM USUARIO_PERFIL WHERE ID_USUARIO IN
  (SELECT ID_USUARIO FROM USUARIO WHERE DS_EMAIL LIKE '%@exemplo.test');
DELETE FROM USUARIO WHERE DS_EMAIL LIKE '%@exemplo.test';
DELETE FROM PRESTADOR WHERE NM_PRESTADOR IN
  ('CLINICA EXEMPLO DIAGNOSTICOS LTDA',
   'CENTRO DE IMAGEM MODELO S/A',
   'MARIA EXEMPLO DA SILVA - FONOAUDIOLOGA');

INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CARDIOVITA SERVIÇOS MÉDICOS LTDA', 'OCS', 'CNPJ',
   '99000001000101', 'Avenida Andromeda', '100',
   'Jardim Satelite', 'Sao Jose dos Campos', 'SP', '12230000');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CENTROCOR - CENTRO DE DIAGNÓSTICO E CIRURGIA DO CORAÇÃO LTDA', 'OCS', 'CNPJ',
   '99000002000148', 'Rua Paraibuna', '137',
   'Centro', 'Taubate', 'SP', '12037013');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CENTRO ONCOLÓGICO DO VALE', 'OCS', 'CNPJ',
   '99000003000192', 'Avenida Cassiano Ricardo', '174',
   'Jardim Aquarius', 'Jacarei', 'SP', '12344026');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CLÍNICA ORTOPÉDICA SANTA LUCIA', 'OCS', 'CNPJ',
   '99000004000137', 'Rua Rubiao Junior', '211',
   'Vila Ema', 'Caçapava', 'SP', '12151039');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('ORTOPEDIA E FISIOTERAPIA MONTELLO LTDA', 'OCS', 'CNPJ',
   '99000005000181', 'Avenida Sao Joao', '248',
   'Jardim Esplanada', 'Sao Jose dos Campos', 'SP', '12258052');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('RAAJ8 SERVIÇOS EM OFTALMOLOGIA', 'OCS', 'CNPJ',
   '99000006000126', 'Rua Doutor Joao Guilhermino', '285',
   'Vila Adyana', 'Taubate', 'SP', '12065065');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CLÍNICA DE UROGINECOLOGIA', 'OCS', 'CNPJ',
   '99000007000170', 'Avenida Doutor Nelson d''Avila', '322',
   'Bosque dos Eucaliptos', 'Jacarei', 'SP', '12372078');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('IPMMI-HOSPITAL MATERNO INFANTIL ANTONINHO DA ROCHA MARMO', 'OCS', 'CNPJ',
   '99000008000115', 'Rua Euclides Miragaia', '359',
   'Jardim Satelite', 'Caçapava', 'SP', '12179091');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('FISIO VIP CLIN LTDA', 'OCS', 'CNPJ',
   '99000009000160', 'Avenida Engenheiro Sebastiao Gualberto', '396',
   'Centro', 'Sao Jose dos Campos', 'SP', '12286104');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('LABORATÓRIO DE ANÁLISES CLÍNICAS SÃO JOSE', 'OCS', 'CNPJ',
   '99000010000194', 'Rua Coronel Jose Monteiro', '433',
   'Jardim Aquarius', 'Taubate', 'SP', '12093117');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('M.A. MONTANHA RUGGERI LABORATÓRIO - EPP', 'OCS', 'CNPJ',
   '99000011000139', 'Avenida Andromeda', '470',
   'Vila Ema', 'Jacarei', 'SP', '12300130');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CLARO E MARTINS CLÍNICA ODONTOLÓGICA LTDA', 'OCS', 'CNPJ',
   '99000012000183', 'Rua Paraibuna', '507',
   'Jardim Esplanada', 'Caçapava', 'SP', '12107143');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('L&L PSICOLOGIA LTDA', 'OCS', 'CNPJ',
   '99000013000128', 'Avenida Cassiano Ricardo', '544',
   'Vila Adyana', 'Sao Jose dos Campos', 'SP', '12214156');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('HOME CARE SILVA E SILVA ASSISTÊNCIA A SAÚDE', 'OCS', 'CNPJ',
   '99000014000172', 'Rua Rubiao Junior', '581',
   'Bosque dos Eucaliptos', 'Taubate', 'SP', '12021169');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('SÃO JOSE ASSISTÊNCIA A SAÚDE EIRELI - HOME CARE', 'OCS', 'CNPJ',
   '99000015000117', 'Avenida Sao Joao', '618',
   'Jardim Satelite', 'Jacarei', 'SP', '12328182');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('ONCOVIDA ONCO-HEMATOLOGIA LTDA', 'OCS', 'CNPJ',
   '99000016000161', 'Rua Doutor Joao Guilhermino', '655',
   'Centro', 'Caçapava', 'SP', '12135195');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('ASSOCIAÇÃO DE EQUOTERAPIA SAÚDE E EDUCAÇÃO TROTANDO EM FRENTE LTDA', 'OCS', 'CNPJ',
   '99000017000106', 'Avenida Doutor Nelson d''Avila', '692',
   'Jardim Aquarius', 'Sao Jose dos Campos', 'SP', '12242208');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('SERVASC CLÍNICA VASCULAR LTDA', 'OCS', 'CNPJ',
   '99000018000150', 'Rua Euclides Miragaia', '729',
   'Vila Ema', 'Taubate', 'SP', '12049221');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('ENDOCARD CLÍNICA MÉDICA D.B.F. LTDA', 'OCS', 'CNPJ',
   '99000019000103', 'Avenida Engenheiro Sebastiao Gualberto', '766',
   'Jardim Esplanada', 'Jacarei', 'SP', '12356234');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('COE CENTRO DE OLHOS E ESPECIALIDADES', 'OCS', 'CNPJ',
   '99000020000120', 'Rua Coronel Jose Monteiro', '803',
   'Vila Adyana', 'Caçapava', 'SP', '12163247');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('PERSONALCLIN - PRESTAÇÃO DE SERVIÇOS DE SAÚDE EIRELI', 'OCS', 'CNPJ',
   '99000021000174', 'Avenida Andromeda', '840',
   'Bosque dos Eucaliptos', 'Sao Jose dos Campos', 'SP', '12270260');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CLÍNICA DE EMAGRECIMENTO E BEM ESTAR', 'OCS', 'CNPJ',
   '99000022000119', 'Rua Paraibuna', '877',
   'Jardim Satelite', 'Taubate', 'SP', '12077273');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('ODONTO CLEAN LTDA', 'OCS', 'CNPJ',
   '99000023000163', 'Avenida Cassiano Ricardo', '914',
   'Centro', 'Jacarei', 'SP', '12384286');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CEMEV-CLÍNICA DE ESPECIALIDADES MÉDICAS DO VALE LTDA', 'OCS', 'CNPJ',
   '99000024000108', 'Rua Rubiao Junior', '951',
   'Jardim Aquarius', 'Caçapava', 'SP', '12191299');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('REABILITAR SAÚDE CLÍNICA DE FISIOTERAPIA LTDA', 'OCS', 'CNPJ',
   '99000025000152', 'Avenida Sao Joao', '988',
   'Vila Ema', 'Sao Jose dos Campos', 'SP', '12298312');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CENTRO MÉDICO E OFTALMOLÓGICO ALMEIDA CREPALDI LTDA', 'OCS', 'CNPJ',
   '99000026000105', 'Rua Doutor Joao Guilhermino', '1025',
   'Jardim Esplanada', 'Taubate', 'SP', '12005325');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('QUAGGIO SERVIÇOS ODONTOLÓGICOS LTDA', 'OCS', 'CNPJ',
   '99000027000141', 'Avenida Doutor Nelson d''Avila', '1062',
   'Vila Adyana', 'Jacarei', 'SP', '12312338');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('MASTERCLIN CLÍNICA FISIOTERAPÊUTICA LTDA', 'OCS', 'CNPJ',
   '99000028000196', 'Rua Euclides Miragaia', '1099',
   'Bosque dos Eucaliptos', 'Caçapava', 'SP', '12119351');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('PLANI DIAGNÓSTICOS MÉDICOS LTDA', 'OCS', 'CNPJ',
   '99000029000130', 'Avenida Engenheiro Sebastiao Gualberto', '1136',
   'Jardim Satelite', 'Sao Jose dos Campos', 'SP', '12226364');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CLÍNICA OFTALMOLÓGICA ALMEIDA E VENÂNCIO LTDA', 'OCS', 'CNPJ',
   '99000030000165', 'Rua Coronel Jose Monteiro', '1173',
   'Centro', 'Taubate', 'SP', '12033377');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CENTRO DE VALORIZAÇÃO DA VIDA FRANCISCA JULIA', 'OCS', 'CNPJ',
   '99000031000100', 'Avenida Andromeda', '1210',
   'Jardim Aquarius', 'Jacarei', 'SP', '12340390');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('INSTITUTO DE RADIOTERAPIA DO VALE DO PARAÍBA LTDA', 'OCS', 'CNPJ',
   '99000032000154', 'Rua Paraibuna', '1247',
   'Vila Ema', 'Caçapava', 'SP', '12147403');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('Dr. LUIZ GUSTAVO CENTURION DE MOURA', 'PSA', 'CPF',
   '99900000188', 'Avenida Cassiano Ricardo', '1284',
   'Jardim Esplanada', 'Sao Jose dos Campos', 'SP', '12254416');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('Dra. NAZARÉ JAQUELINE DE LIMA MARQUES', 'PSA', 'CPF',
   '99900000269', 'Rua Rubiao Junior', '1321',
   'Vila Adyana', 'Taubate', 'SP', '12061429');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('VID LAP SS LTDA', 'OCS', 'CNPJ',
   '99000033000107', 'Avenida Sao Joao', '1358',
   'Bosque dos Eucaliptos', 'Jacarei', 'SP', '12368442');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CENTRO DIAGNÓSTICO ANDRADE', 'OCS', 'CNPJ',
   '99000034000143', 'Rua Doutor Joao Guilhermino', '1395',
   'Jardim Satelite', 'Caçapava', 'SP', '12175455');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('HEMACORE - SERVIÇO DE HEMATOLOGIA DE SJC LTDA', 'OCS', 'CNPJ',
   '99000035000198', 'Avenida Doutor Nelson d''Avila', '1432',
   'Centro', 'Sao Jose dos Campos', 'SP', '12282468');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('SERVIÇOS DE TRATAMENTO AO CÂNCER DE TAUBATÉ LTDA', 'OCS', 'CNPJ',
   '99000036000132', 'Rua Euclides Miragaia', '1469',
   'Jardim Aquarius', 'Taubate', 'SP', '12089481');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('HOSPITAL DE OLHOS DO VALE - EXCIMER LASER VALE DO PARAIBA LTDA', 'OCS', 'CNPJ',
   '99000037000187', 'Avenida Engenheiro Sebastiao Gualberto', '1506',
   'Vila Ema', 'Jacarei', 'SP', '12396494');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('DRA. HERIKA THAMILLA CAMARGO ALVES ALBANO FARIA', 'PSA', 'CPF',
   '99900000340', 'Rua Coronel Jose Monteiro', '1543',
   'Jardim Esplanada', 'Caçapava', 'SP', '12103507');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('IPMMI-HOSPITALPIO XII', 'OCS', 'CNPJ',
   '99000038000121', 'Avenida Andromeda', '1580',
   'Vila Adyana', 'Sao Jose dos Campos', 'SP', '12210520');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('NXT TLECONSULTA', 'OCS', 'CNPJ',
   '99000039000176', 'Rua Paraibuna', '1617',
   'Bosque dos Eucaliptos', 'Taubate', 'SP', '12017533');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CLÍNICA DE NEURODESENVOLVIMENTO TEAR MAIS', 'OCS', 'CNPJ',
   '99000040000109', 'Avenida Cassiano Ricardo', '1654',
   'Jardim Satelite', 'Jacarei', 'SP', '12324546');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CLÍNICA PEQUENO GESTO', 'OCS', 'CNPJ',
   '99000041000145', 'Rua Rubiao Junior', '1691',
   'Centro', 'Caçapava', 'SP', '12131559');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CLÍNICA ROTA DA APRENDIZAGEM', 'OCS', 'CNPJ',
   '99000042000190', 'Avenida Sao Joao', '1728',
   'Jardim Aquarius', 'Sao Jose dos Campos', 'SP', '12238572');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CLÍNICA AUMERA', 'OCS', 'CNPJ',
   '99000043000134', 'Rua Doutor Joao Guilhermino', '1765',
   'Vila Ema', 'Taubate', 'SP', '12045585');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('WK RADIOLOGIA', 'OCS', 'CNPJ',
   '99000044000189', 'Avenida Doutor Nelson d''Avila', '1802',
   'Jardim Esplanada', 'Jacarei', 'SP', '12352598');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('ESPAÇO NEURO&PSI LTDA', 'OCS', 'CNPJ',
   '99000045000123', 'Rua Euclides Miragaia', '1839',
   'Vila Adyana', 'Caçapava', 'SP', '12159611');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('CLINÍCA MÉDICA ESSENZA LTDA', 'OCS', 'CNPJ',
   '99000046000178', 'Avenida Engenheiro Sebastiao Gualberto', '1876',
   'Bosque dos Eucaliptos', 'Sao Jose dos Campos', 'SP', '12266624');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('PRO IMAGEM PINDA', 'OCS', 'CNPJ',
   '99000047000112', 'Rua Coronel Jose Monteiro', '113',
   'Jardim Satelite', 'Taubate', 'SP', '12073637');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('PRO IMAGEM TAUBATÉ', 'OCS', 'CNPJ',
   '99000048000167', 'Avenida Andromeda', '150',
   'Centro', 'Jacarei', 'SP', '12380650');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('INTERDIÁLOGOS TRANSFORMAÇÃO PLURAL LTDA', 'OCS', 'CNPJ',
   '99000049000101', 'Rua Paraibuna', '187',
   'Jardim Aquarius', 'Caçapava', 'SP', '12187663');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('KARINA PRATES', 'OCS', 'CNPJ',
   '99000050000136', 'Avenida Cassiano Ricardo', '224',
   'Vila Ema', 'Sao Jose dos Campos', 'SP', '12294676');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('3B BASLER', 'OCS', 'CNPJ',
   '99000051000180', 'Rua Rubiao Junior', '261',
   'Jardim Esplanada', 'Taubate', 'SP', '12001689');
INSERT INTO PRESTADOR (NM_PRESTADOR, TP_PRESTADOR, TP_DOCUMENTO,
  NR_DOCUMENTO, DS_LOGRADOURO, NR_ENDERECO, NM_BAIRRO, NM_CIDADE,
  SG_UF, NR_CEP) VALUES
  ('SINAPSE', 'OCS', 'CNPJ',
   '99000052000125', 'Avenida Sao Joao', '298',
   'Vila Adyana', 'Jacarei', 'SP', '12308702');

INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Cardiovita Servicos Medicos Ltda', 'responsavel@cardiovita.test',
   '(12) 3900-1000', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CARDIOVITA SERVIÇOS MÉDICOS LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Faturamento Cardiovita Servicos Medicos Ltda', 'faturamento@cardiovita.test',
   '(12) 99900-2000', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CARDIOVITA SERVIÇOS MÉDICOS LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Centrocor - Centro De Diagnostico E Ciru', 'responsavel@centrocor.test',
   '(12) 3900-1001', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CENTROCOR - CENTRO DE DIAGNÓSTICO E CIRURGIA DO CORAÇÃO LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Centro Oncologico Do Vale', 'responsavel@oncologico.test',
   '(12) 3900-1002', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CENTRO ONCOLÓGICO DO VALE';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Clinica Ortopedica Santa Lucia', 'responsavel@ortopedica.test',
   '(12) 3900-1003', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CLÍNICA ORTOPÉDICA SANTA LUCIA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Ortopedia E Fisioterapia Montello Ltda', 'responsavel@ortopedia.test',
   '(12) 3900-1004', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'ORTOPEDIA E FISIOTERAPIA MONTELLO LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Raaj8 Servicos Em Oftalmologia', 'responsavel@raaj.test',
   '(12) 3900-1005', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'RAAJ8 SERVIÇOS EM OFTALMOLOGIA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Faturamento Raaj8 Servicos Em Oftalmologia', 'faturamento@raaj.test',
   '(12) 99900-2005', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'RAAJ8 SERVIÇOS EM OFTALMOLOGIA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Clinica De Uroginecologia', 'responsavel@uroginecologia.test',
   '(12) 3900-1006', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CLÍNICA DE UROGINECOLOGIA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Ipmmi-Hospital Materno Infantil Antoninh', 'responsavel@ipmmi.test',
   '(12) 3900-1007', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'IPMMI-HOSPITAL MATERNO INFANTIL ANTONINHO DA ROCHA MARMO';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Fisio Vip Clin Ltda', 'responsavel@fisio.test',
   '(12) 3900-1008', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'FISIO VIP CLIN LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Laboratorio De Analises Clinicas Sao Jos', 'responsavel@laboratorio.test',
   '(12) 3900-1009', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'LABORATÓRIO DE ANÁLISES CLÍNICAS SÃO JOSE';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel M.A. Montanha Ruggeri Laboratorio - Epp', 'responsavel@m.test',
   '(12) 3900-1010', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'M.A. MONTANHA RUGGERI LABORATÓRIO - EPP';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Faturamento M.A. Montanha Ruggeri Laboratorio - Epp', 'faturamento@m.test',
   '(12) 99900-2010', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'M.A. MONTANHA RUGGERI LABORATÓRIO - EPP';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Claro E Martins Clinica Odontologica Ltd', 'responsavel@claro.test',
   '(12) 3900-1011', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CLARO E MARTINS CLÍNICA ODONTOLÓGICA LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel L&L Psicologia Ltda', 'responsavel@l.test',
   '(12) 3900-1012', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'L&L PSICOLOGIA LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Home Care Silva E Silva Assistencia A Sa', 'responsavel@home.test',
   '(12) 3900-1013', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'HOME CARE SILVA E SILVA ASSISTÊNCIA A SAÚDE';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Sao Jose Assistencia A Saude Eireli - Ho', 'responsavel@sao.test',
   '(12) 3900-1014', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'SÃO JOSE ASSISTÊNCIA A SAÚDE EIRELI - HOME CARE';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Oncovida Onco-Hematologia Ltda', 'responsavel@oncovida.test',
   '(12) 3900-1015', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'ONCOVIDA ONCO-HEMATOLOGIA LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Faturamento Oncovida Onco-Hematologia Ltda', 'faturamento@oncovida.test',
   '(12) 99900-2015', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'ONCOVIDA ONCO-HEMATOLOGIA LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Associacao De Equoterapia Saude E Educac', 'responsavel@associacao.test',
   '(12) 3900-1016', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'ASSOCIAÇÃO DE EQUOTERAPIA SAÚDE E EDUCAÇÃO TROTANDO EM FRENTE LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Servasc Clinica Vascular Ltda', 'responsavel@servasc.test',
   '(12) 3900-1017', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'SERVASC CLÍNICA VASCULAR LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Endocard Clinica Medica D.B.F. Ltda', 'responsavel@endocard.test',
   '(12) 3900-1018', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'ENDOCARD CLÍNICA MÉDICA D.B.F. LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Coe Centro De Olhos E Especialidades', 'responsavel@coe.test',
   '(12) 3900-1019', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'COE CENTRO DE OLHOS E ESPECIALIDADES';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Personalclin - Prestacao De Servicos De ', 'responsavel@personalclin.test',
   '(12) 3900-1020', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'PERSONALCLIN - PRESTAÇÃO DE SERVIÇOS DE SAÚDE EIRELI';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Faturamento Personalclin - Prestacao De Servicos De ', 'faturamento@personalclin.test',
   '(12) 99900-2020', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'PERSONALCLIN - PRESTAÇÃO DE SERVIÇOS DE SAÚDE EIRELI';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Clinica De Emagrecimento E Bem Estar', 'responsavel@emagrecimento.test',
   '(12) 3900-1021', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CLÍNICA DE EMAGRECIMENTO E BEM ESTAR';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Odonto Clean Ltda', 'responsavel@odonto.test',
   '(12) 3900-1022', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'ODONTO CLEAN LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Cemev-Clinica De Especialidades Medicas ', 'responsavel@cemev.test',
   '(12) 3900-1023', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CEMEV-CLÍNICA DE ESPECIALIDADES MÉDICAS DO VALE LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Reabilitar Saude Clinica De Fisioterapia', 'responsavel@reabilitar.test',
   '(12) 3900-1024', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'REABILITAR SAÚDE CLÍNICA DE FISIOTERAPIA LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Centro Medico E Oftalmologico Almeida Cr', 'responsavel@medico.test',
   '(12) 3900-1025', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CENTRO MÉDICO E OFTALMOLÓGICO ALMEIDA CREPALDI LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Faturamento Centro Medico E Oftalmologico Almeida Cr', 'faturamento@medico.test',
   '(12) 99900-2025', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CENTRO MÉDICO E OFTALMOLÓGICO ALMEIDA CREPALDI LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Quaggio Servicos Odontologicos Ltda', 'responsavel@quaggio.test',
   '(12) 3900-1026', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'QUAGGIO SERVIÇOS ODONTOLÓGICOS LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Masterclin Clinica Fisioterapeutica Ltda', 'responsavel@masterclin.test',
   '(12) 3900-1027', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'MASTERCLIN CLÍNICA FISIOTERAPÊUTICA LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Plani Diagnosticos Medicos Ltda', 'responsavel@plani.test',
   '(12) 3900-1028', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'PLANI DIAGNÓSTICOS MÉDICOS LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Clinica Oftalmologica Almeida E Venancio', 'responsavel@oftalmologica.test',
   '(12) 3900-1029', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CLÍNICA OFTALMOLÓGICA ALMEIDA E VENÂNCIO LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Centro De Valorizacao Da Vida Francisca ', 'responsavel@valorizacao.test',
   '(12) 3900-1030', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CENTRO DE VALORIZAÇÃO DA VIDA FRANCISCA JULIA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Faturamento Centro De Valorizacao Da Vida Francisca ', 'faturamento@valorizacao.test',
   '(12) 99900-2030', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CENTRO DE VALORIZAÇÃO DA VIDA FRANCISCA JULIA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Instituto De Radioterapia Do Vale Do Par', 'responsavel@instituto.test',
   '(12) 3900-1031', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'INSTITUTO DE RADIOTERAPIA DO VALE DO PARAÍBA LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Dr. Luiz Gustavo Centurion De Moura', 'responsavel@luiz.test',
   '(12) 3900-1032', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'Dr. LUIZ GUSTAVO CENTURION DE MOURA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Dra. Nazare Jaqueline De Lima Marques', 'responsavel@nazare.test',
   '(12) 3900-1033', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'Dra. NAZARÉ JAQUELINE DE LIMA MARQUES';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Vid Lap Ss Ltda', 'responsavel@vid.test',
   '(12) 3900-1034', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'VID LAP SS LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Centro Diagnostico Andrade', 'responsavel@diagnostico.test',
   '(12) 3900-1035', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CENTRO DIAGNÓSTICO ANDRADE';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Faturamento Centro Diagnostico Andrade', 'faturamento@diagnostico.test',
   '(12) 99900-2035', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CENTRO DIAGNÓSTICO ANDRADE';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Hemacore - Servico De Hematologia De Sjc', 'responsavel@hemacore.test',
   '(12) 3900-1036', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'HEMACORE - SERVIÇO DE HEMATOLOGIA DE SJC LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Servicos De Tratamento Ao Cancer De Taub', 'responsavel@servicos.test',
   '(12) 3900-1037', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'SERVIÇOS DE TRATAMENTO AO CÂNCER DE TAUBATÉ LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Hospital De Olhos Do Vale - Excimer Lase', 'responsavel@olhos.test',
   '(12) 3900-1038', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'HOSPITAL DE OLHOS DO VALE - EXCIMER LASER VALE DO PARAIBA LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Dra. Herika Thamilla Camargo Alves Alban', 'responsavel@herika.test',
   '(12) 3900-1039', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'DRA. HERIKA THAMILLA CAMARGO ALVES ALBANO FARIA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Ipmmi-Hospitalpio Xii', 'responsavel@ipmmi2.test',
   '(12) 3900-1040', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'IPMMI-HOSPITALPIO XII';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Faturamento Ipmmi-Hospitalpio Xii', 'faturamento@ipmmi2.test',
   '(12) 99900-2040', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'IPMMI-HOSPITALPIO XII';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Nxt Tleconsulta', 'responsavel@nxt.test',
   '(12) 3900-1041', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'NXT TLECONSULTA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Clinica De Neurodesenvolvimento Tear Mai', 'responsavel@neurodesenvolvimen.test',
   '(12) 3900-1042', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CLÍNICA DE NEURODESENVOLVIMENTO TEAR MAIS';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Clinica Pequeno Gesto', 'responsavel@pequeno.test',
   '(12) 3900-1043', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CLÍNICA PEQUENO GESTO';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Clinica Rota Da Aprendizagem', 'responsavel@rota.test',
   '(12) 3900-1044', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CLÍNICA ROTA DA APRENDIZAGEM';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Clinica Aumera', 'responsavel@aumera.test',
   '(12) 3900-1045', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CLÍNICA AUMERA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Faturamento Clinica Aumera', 'faturamento@aumera.test',
   '(12) 99900-2045', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CLÍNICA AUMERA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Wk Radiologia', 'responsavel@wk.test',
   '(12) 3900-1046', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'WK RADIOLOGIA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Espaco Neuro&Psi Ltda', 'responsavel@espaco.test',
   '(12) 3900-1047', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'ESPAÇO NEURO&PSI LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Clinica Medica Essenza Ltda', 'responsavel@medica.test',
   '(12) 3900-1048', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'CLINÍCA MÉDICA ESSENZA LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Pro Imagem Pinda', 'responsavel@pro.test',
   '(12) 3900-1049', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'PRO IMAGEM PINDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Pro Imagem Taubate', 'responsavel@pro2.test',
   '(12) 3900-1050', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'PRO IMAGEM TAUBATÉ';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Faturamento Pro Imagem Taubate', 'faturamento@pro2.test',
   '(12) 99900-2050', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'PRO IMAGEM TAUBATÉ';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Interdialogos Transformacao Plural Ltda', 'responsavel@interdialogos.test',
   '(12) 3900-1051', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'INTERDIÁLOGOS TRANSFORMAÇÃO PLURAL LTDA';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Karina Prates', 'responsavel@karina.test',
   '(12) 3900-1052', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'KARINA PRATES';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel 3B Basler', 'responsavel@b.test',
   '(12) 3900-1053', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = '3B BASLER';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH)
SELECT ID_PRESTADOR, 'Responsavel Sinapse', 'responsavel@sinapse.test',
   '(12) 3900-1054', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
  FROM PRESTADOR WHERE NM_PRESTADOR = 'SINAPSE';
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH) VALUES
  (NULL, 'Administrador FUSEx', 'admin@fusex.test',
   '(12) 3900-0001', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy');
INSERT INTO USUARIO (ID_PRESTADOR, NM_USUARIO, DS_EMAIL,
  NR_TELEFONE, DS_SENHA_HASH) VALUES
  (NULL, 'Analista de Lisura', 'lisura@fusex.test',
   '(12) 3900-0002', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy');

INSERT INTO USUARIO_PERFIL (ID_USUARIO, CD_PERFIL)
SELECT ID_USUARIO, 'PRESTADOR' FROM USUARIO
 WHERE ID_PRESTADOR IS NOT NULL;

INSERT INTO USUARIO_PERFIL (ID_USUARIO, CD_PERFIL)
SELECT ID_USUARIO, 'ADMIN' FROM USUARIO
 WHERE LOWER(DS_EMAIL) = 'admin@fusex.test';

INSERT INTO USUARIO_PERFIL (ID_USUARIO, CD_PERFIL)
SELECT ID_USUARIO, 'LISURA' FROM USUARIO
 WHERE LOWER(DS_EMAIL) IN ('admin@fusex.test','lisura@fusex.test');

COMMIT;
