spring.appli# Configurações de Conexão com o Oracle (Docker)
spring.datasource.url=jdbc:oracle:thin:@//localhost:1522/FREEPDB1
spring.datasource.username=fatec_user
spring.datasource.password=fatec_user_123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configurações do Hibernate / Comportamento
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect